/*
 * API для аптечных сетей
 *
 * Авторизация по токену, используйте заголовок          Authorization: Bearer токен         пример:          Authorization: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU          Для того чтобы работать с API через интерфейс swagger (ниже, по кнопке Try it out),         нажмите кнопку Authorize и укажите токен в формате Bearer токен.         Пример: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU 
 *
 * The version of the OpenAPI document: v2
 * Contact: info@pharm-zakaz.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DetailedProduct
    /// </summary>
    [DataContract]
    public partial class DetailedProduct :  IEquatable<DetailedProduct>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetailedProduct" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DetailedProduct() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DetailedProduct" /> class.
        /// </summary>
        /// <param name="uniqueId">uniqueId (required).</param>
        /// <param name="productId">productId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="ean">ean (required).</param>
        /// <param name="gtin">gtin (required).</param>
        /// <param name="vat">vat (required).</param>
        /// <param name="price">price (required).</param>
        /// <param name="priceWithVAT">priceWithVAT (required).</param>
        /// <param name="distributorId">distributorId (required).</param>
        /// <param name="expirationDate">expirationDate (required).</param>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="minOrder">minOrder (required).</param>
        /// <param name="multiplicity">multiplicity (required).</param>
        /// <param name="bonus">bonus (required).</param>
        /// <param name="discount">discount (required).</param>
        /// <param name="potentialPriceWithOffers">potentialPriceWithOffers.</param>
        /// <param name="isOffer">isOffer (required).</param>
        /// <param name="bonusMaxMonthOrderAmount">bonusMaxMonthOrderAmount.</param>
        /// <param name="potentialPriceTotal">potentialPriceTotal.</param>
        /// <param name="manufacturer">manufacturer (required).</param>
        /// <param name="vatSum">vatSum (required).</param>
        /// <param name="ingredients">ingredients (required).</param>
        /// <param name="country">country (required).</param>
        /// <param name="packageAmount">packageAmount (required).</param>
        /// <param name="storageConditions">storageConditions (required).</param>
        /// <param name="storagePeriod">storagePeriod (required).</param>
        /// <param name="weight">weight (required).</param>
        /// <param name="brand">brand (required).</param>
        /// <param name="category">category (required).</param>
        /// <param name="group">group (required).</param>
        /// <param name="edl">edl (required).</param>
        /// <param name="seasonal">seasonal (required).</param>
        /// <param name="inn">inn (required).</param>
        /// <param name="tvAdv">tvAdv (required).</param>
        /// <param name="novelty">novelty (required).</param>
        /// <param name="bestseller">bestseller (required).</param>
        /// <param name="offers">offers (required).</param>
        public DetailedProduct(string uniqueId = default(string), int productId = default(int), string name = default(string), string ean = default(string), string gtin = default(string), decimal vat = default(decimal), decimal price = default(decimal), decimal priceWithVAT = default(decimal), int distributorId = default(int), DateTime expirationDate = default(DateTime), int quantity = default(int), int minOrder = default(int), int multiplicity = default(int), decimal bonus = default(decimal), decimal discount = default(decimal), decimal potentialPriceWithOffers = default(decimal), bool isOffer = default(bool), decimal bonusMaxMonthOrderAmount = default(decimal), decimal potentialPriceTotal = default(decimal), string manufacturer = default(string), decimal vatSum = default(decimal), string ingredients = default(string), string country = default(string), int packageAmount = default(int), string storageConditions = default(string), int storagePeriod = default(int), decimal weight = default(decimal), string brand = default(string), string category = default(string), string group = default(string), bool edl = default(bool), bool seasonal = default(bool), bool inn = default(bool), bool tvAdv = default(bool), bool novelty = default(bool), bool bestseller = default(bool), List<Offer> offers = default(List<Offer>))
        {
            // to ensure "uniqueId" is required (not null)
            if (uniqueId == null)
            {
                throw new InvalidDataException("uniqueId is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.UniqueId = uniqueId;
            }

            // to ensure "productId" is required (not null)
            if (productId == null)
            {
                throw new InvalidDataException("productId is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.ProductId = productId;
            }

            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Name = name;
            }

            // to ensure "ean" is required (not null)
            if (ean == null)
            {
                throw new InvalidDataException("ean is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Ean = ean;
            }

            // to ensure "gtin" is required (not null)
            if (gtin == null)
            {
                throw new InvalidDataException("gtin is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Gtin = gtin;
            }

            // to ensure "vat" is required (not null)
            if (vat == null)
            {
                throw new InvalidDataException("vat is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Vat = vat;
            }

            // to ensure "price" is required (not null)
            if (price == null)
            {
                throw new InvalidDataException("price is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Price = price;
            }

            // to ensure "priceWithVAT" is required (not null)
            if (priceWithVAT == null)
            {
                throw new InvalidDataException("priceWithVAT is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.PriceWithVAT = priceWithVAT;
            }

            // to ensure "distributorId" is required (not null)
            if (distributorId == null)
            {
                throw new InvalidDataException("distributorId is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.DistributorId = distributorId;
            }

            // to ensure "expirationDate" is required (not null)
            if (expirationDate == null)
            {
                throw new InvalidDataException("expirationDate is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.ExpirationDate = expirationDate;
            }

            // to ensure "quantity" is required (not null)
            if (quantity == null)
            {
                throw new InvalidDataException("quantity is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Quantity = quantity;
            }

            // to ensure "minOrder" is required (not null)
            if (minOrder == null)
            {
                throw new InvalidDataException("minOrder is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.MinOrder = minOrder;
            }

            // to ensure "multiplicity" is required (not null)
            if (multiplicity == null)
            {
                throw new InvalidDataException("multiplicity is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Multiplicity = multiplicity;
            }

            // to ensure "bonus" is required (not null)
            if (bonus == null)
            {
                throw new InvalidDataException("bonus is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Bonus = bonus;
            }

            // to ensure "discount" is required (not null)
            if (discount == null)
            {
                throw new InvalidDataException("discount is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Discount = discount;
            }

            // to ensure "isOffer" is required (not null)
            if (isOffer == null)
            {
                throw new InvalidDataException("isOffer is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.IsOffer = isOffer;
            }

            // to ensure "manufacturer" is required (not null)
            if (manufacturer == null)
            {
                throw new InvalidDataException("manufacturer is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Manufacturer = manufacturer;
            }

            // to ensure "vatSum" is required (not null)
            if (vatSum == null)
            {
                throw new InvalidDataException("vatSum is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.VatSum = vatSum;
            }

            // to ensure "ingredients" is required (not null)
            if (ingredients == null)
            {
                throw new InvalidDataException("ingredients is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Ingredients = ingredients;
            }

            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new InvalidDataException("country is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Country = country;
            }

            // to ensure "packageAmount" is required (not null)
            if (packageAmount == null)
            {
                throw new InvalidDataException("packageAmount is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.PackageAmount = packageAmount;
            }

            // to ensure "storageConditions" is required (not null)
            if (storageConditions == null)
            {
                throw new InvalidDataException("storageConditions is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.StorageConditions = storageConditions;
            }

            // to ensure "storagePeriod" is required (not null)
            if (storagePeriod == null)
            {
                throw new InvalidDataException("storagePeriod is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.StoragePeriod = storagePeriod;
            }

            // to ensure "weight" is required (not null)
            if (weight == null)
            {
                throw new InvalidDataException("weight is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Weight = weight;
            }

            // to ensure "brand" is required (not null)
            if (brand == null)
            {
                throw new InvalidDataException("brand is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Brand = brand;
            }

            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new InvalidDataException("category is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Category = category;
            }

            // to ensure "group" is required (not null)
            if (group == null)
            {
                throw new InvalidDataException("group is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Group = group;
            }

            // to ensure "edl" is required (not null)
            if (edl == null)
            {
                throw new InvalidDataException("edl is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Edl = edl;
            }

            // to ensure "seasonal" is required (not null)
            if (seasonal == null)
            {
                throw new InvalidDataException("seasonal is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Seasonal = seasonal;
            }

            // to ensure "inn" is required (not null)
            if (inn == null)
            {
                throw new InvalidDataException("inn is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Inn = inn;
            }

            // to ensure "tvAdv" is required (not null)
            if (tvAdv == null)
            {
                throw new InvalidDataException("tvAdv is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.TvAdv = tvAdv;
            }

            // to ensure "novelty" is required (not null)
            if (novelty == null)
            {
                throw new InvalidDataException("novelty is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Novelty = novelty;
            }

            // to ensure "bestseller" is required (not null)
            if (bestseller == null)
            {
                throw new InvalidDataException("bestseller is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Bestseller = bestseller;
            }

            // to ensure "offers" is required (not null)
            if (offers == null)
            {
                throw new InvalidDataException("offers is a required property for DetailedProduct and cannot be null");
            }
            else
            {
                this.Offers = offers;
            }

            this.PotentialPriceWithOffers = potentialPriceWithOffers;
            this.BonusMaxMonthOrderAmount = bonusMaxMonthOrderAmount;
            this.PotentialPriceTotal = potentialPriceTotal;
        }

        /// <summary>
        /// Gets or Sets UniqueId
        /// </summary>
        [DataMember(Name="unique_id", EmitDefaultValue=true)]
        public string UniqueId { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name="product_id", EmitDefaultValue=true)]
        public int ProductId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Ean
        /// </summary>
        [DataMember(Name="ean", EmitDefaultValue=true)]
        public string Ean { get; set; }

        /// <summary>
        /// Gets or Sets Gtin
        /// </summary>
        [DataMember(Name="gtin", EmitDefaultValue=true)]
        public string Gtin { get; set; }

        /// <summary>
        /// Gets or Sets Vat
        /// </summary>
        [DataMember(Name="vat", EmitDefaultValue=true)]
        public decimal Vat { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="price", EmitDefaultValue=true)]
        public decimal Price { get; set; }

        /// <summary>
        /// Gets or Sets PriceWithVAT
        /// </summary>
        [DataMember(Name="price_with_VAT", EmitDefaultValue=true)]
        public decimal PriceWithVAT { get; set; }

        /// <summary>
        /// Gets or Sets DistributorId
        /// </summary>
        [DataMember(Name="distributor_id", EmitDefaultValue=true)]
        public int DistributorId { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationDate
        /// </summary>
        [DataMember(Name="expiration_date", EmitDefaultValue=true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime ExpirationDate { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or Sets MinOrder
        /// </summary>
        [DataMember(Name="min_order", EmitDefaultValue=true)]
        public int MinOrder { get; set; }

        /// <summary>
        /// Gets or Sets Multiplicity
        /// </summary>
        [DataMember(Name="multiplicity", EmitDefaultValue=true)]
        public int Multiplicity { get; set; }

        /// <summary>
        /// Gets or Sets Bonus
        /// </summary>
        [DataMember(Name="bonus", EmitDefaultValue=true)]
        public decimal Bonus { get; set; }

        /// <summary>
        /// Gets or Sets Discount
        /// </summary>
        [DataMember(Name="discount", EmitDefaultValue=true)]
        public decimal Discount { get; set; }

        /// <summary>
        /// Gets or Sets PotentialPriceWithOffers
        /// </summary>
        [DataMember(Name="potential_price_with_offers", EmitDefaultValue=false)]
        public decimal PotentialPriceWithOffers { get; set; }

        /// <summary>
        /// Gets or Sets IsOffer
        /// </summary>
        [DataMember(Name="is_offer", EmitDefaultValue=true)]
        public bool IsOffer { get; set; }

        /// <summary>
        /// Gets or Sets BonusMaxMonthOrderAmount
        /// </summary>
        [DataMember(Name="bonus_max_month_order_amount", EmitDefaultValue=false)]
        public decimal BonusMaxMonthOrderAmount { get; set; }

        /// <summary>
        /// Gets or Sets PotentialPriceTotal
        /// </summary>
        [DataMember(Name="potential_price_total", EmitDefaultValue=false)]
        public decimal PotentialPriceTotal { get; set; }

        /// <summary>
        /// Gets or Sets Manufacturer
        /// </summary>
        [DataMember(Name="manufacturer", EmitDefaultValue=true)]
        public string Manufacturer { get; set; }

        /// <summary>
        /// Gets or Sets VatSum
        /// </summary>
        [DataMember(Name="vat_sum", EmitDefaultValue=true)]
        public decimal VatSum { get; set; }

        /// <summary>
        /// Gets or Sets Ingredients
        /// </summary>
        [DataMember(Name="ingredients", EmitDefaultValue=true)]
        public string Ingredients { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="country", EmitDefaultValue=true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets PackageAmount
        /// </summary>
        [DataMember(Name="package_amount", EmitDefaultValue=true)]
        public int PackageAmount { get; set; }

        /// <summary>
        /// Gets or Sets StorageConditions
        /// </summary>
        [DataMember(Name="storage_conditions", EmitDefaultValue=true)]
        public string StorageConditions { get; set; }

        /// <summary>
        /// Gets or Sets StoragePeriod
        /// </summary>
        [DataMember(Name="storage_period", EmitDefaultValue=true)]
        public int StoragePeriod { get; set; }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [DataMember(Name="weight", EmitDefaultValue=true)]
        public decimal Weight { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name="brand", EmitDefaultValue=true)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=true)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets Group
        /// </summary>
        [DataMember(Name="group", EmitDefaultValue=true)]
        public string Group { get; set; }

        /// <summary>
        /// Gets or Sets Edl
        /// </summary>
        [DataMember(Name="edl", EmitDefaultValue=true)]
        public bool Edl { get; set; }

        /// <summary>
        /// Gets or Sets Seasonal
        /// </summary>
        [DataMember(Name="seasonal", EmitDefaultValue=true)]
        public bool Seasonal { get; set; }

        /// <summary>
        /// Gets or Sets Inn
        /// </summary>
        [DataMember(Name="inn", EmitDefaultValue=true)]
        public bool Inn { get; set; }

        /// <summary>
        /// Gets or Sets TvAdv
        /// </summary>
        [DataMember(Name="tv_adv", EmitDefaultValue=true)]
        public bool TvAdv { get; set; }

        /// <summary>
        /// Gets or Sets Novelty
        /// </summary>
        [DataMember(Name="novelty", EmitDefaultValue=true)]
        public bool Novelty { get; set; }

        /// <summary>
        /// Gets or Sets Bestseller
        /// </summary>
        [DataMember(Name="bestseller", EmitDefaultValue=true)]
        public bool Bestseller { get; set; }

        /// <summary>
        /// Gets or Sets Offers
        /// </summary>
        [DataMember(Name="offers", EmitDefaultValue=true)]
        public List<Offer> Offers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DetailedProduct {\n");
            sb.Append("  UniqueId: ").Append(UniqueId).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Ean: ").Append(Ean).Append("\n");
            sb.Append("  Gtin: ").Append(Gtin).Append("\n");
            sb.Append("  Vat: ").Append(Vat).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  PriceWithVAT: ").Append(PriceWithVAT).Append("\n");
            sb.Append("  DistributorId: ").Append(DistributorId).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  MinOrder: ").Append(MinOrder).Append("\n");
            sb.Append("  Multiplicity: ").Append(Multiplicity).Append("\n");
            sb.Append("  Bonus: ").Append(Bonus).Append("\n");
            sb.Append("  Discount: ").Append(Discount).Append("\n");
            sb.Append("  PotentialPriceWithOffers: ").Append(PotentialPriceWithOffers).Append("\n");
            sb.Append("  IsOffer: ").Append(IsOffer).Append("\n");
            sb.Append("  BonusMaxMonthOrderAmount: ").Append(BonusMaxMonthOrderAmount).Append("\n");
            sb.Append("  PotentialPriceTotal: ").Append(PotentialPriceTotal).Append("\n");
            sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
            sb.Append("  VatSum: ").Append(VatSum).Append("\n");
            sb.Append("  Ingredients: ").Append(Ingredients).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  PackageAmount: ").Append(PackageAmount).Append("\n");
            sb.Append("  StorageConditions: ").Append(StorageConditions).Append("\n");
            sb.Append("  StoragePeriod: ").Append(StoragePeriod).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Edl: ").Append(Edl).Append("\n");
            sb.Append("  Seasonal: ").Append(Seasonal).Append("\n");
            sb.Append("  Inn: ").Append(Inn).Append("\n");
            sb.Append("  TvAdv: ").Append(TvAdv).Append("\n");
            sb.Append("  Novelty: ").Append(Novelty).Append("\n");
            sb.Append("  Bestseller: ").Append(Bestseller).Append("\n");
            sb.Append("  Offers: ").Append(Offers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DetailedProduct);
        }

        /// <summary>
        /// Returns true if DetailedProduct instances are equal
        /// </summary>
        /// <param name="input">Instance of DetailedProduct to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DetailedProduct input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UniqueId == input.UniqueId ||
                    (this.UniqueId != null &&
                    this.UniqueId.Equals(input.UniqueId))
                ) && 
                (
                    this.ProductId == input.ProductId ||
                    (this.ProductId != null &&
                    this.ProductId.Equals(input.ProductId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Ean == input.Ean ||
                    (this.Ean != null &&
                    this.Ean.Equals(input.Ean))
                ) && 
                (
                    this.Gtin == input.Gtin ||
                    (this.Gtin != null &&
                    this.Gtin.Equals(input.Gtin))
                ) && 
                (
                    this.Vat == input.Vat ||
                    (this.Vat != null &&
                    this.Vat.Equals(input.Vat))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                ) && 
                (
                    this.PriceWithVAT == input.PriceWithVAT ||
                    (this.PriceWithVAT != null &&
                    this.PriceWithVAT.Equals(input.PriceWithVAT))
                ) && 
                (
                    this.DistributorId == input.DistributorId ||
                    (this.DistributorId != null &&
                    this.DistributorId.Equals(input.DistributorId))
                ) && 
                (
                    this.ExpirationDate == input.ExpirationDate ||
                    (this.ExpirationDate != null &&
                    this.ExpirationDate.Equals(input.ExpirationDate))
                ) && 
                (
                    this.Quantity == input.Quantity ||
                    (this.Quantity != null &&
                    this.Quantity.Equals(input.Quantity))
                ) && 
                (
                    this.MinOrder == input.MinOrder ||
                    (this.MinOrder != null &&
                    this.MinOrder.Equals(input.MinOrder))
                ) && 
                (
                    this.Multiplicity == input.Multiplicity ||
                    (this.Multiplicity != null &&
                    this.Multiplicity.Equals(input.Multiplicity))
                ) && 
                (
                    this.Bonus == input.Bonus ||
                    (this.Bonus != null &&
                    this.Bonus.Equals(input.Bonus))
                ) && 
                (
                    this.Discount == input.Discount ||
                    (this.Discount != null &&
                    this.Discount.Equals(input.Discount))
                ) && 
                (
                    this.PotentialPriceWithOffers == input.PotentialPriceWithOffers ||
                    (this.PotentialPriceWithOffers != null &&
                    this.PotentialPriceWithOffers.Equals(input.PotentialPriceWithOffers))
                ) && 
                (
                    this.IsOffer == input.IsOffer ||
                    (this.IsOffer != null &&
                    this.IsOffer.Equals(input.IsOffer))
                ) && 
                (
                    this.BonusMaxMonthOrderAmount == input.BonusMaxMonthOrderAmount ||
                    (this.BonusMaxMonthOrderAmount != null &&
                    this.BonusMaxMonthOrderAmount.Equals(input.BonusMaxMonthOrderAmount))
                ) && 
                (
                    this.PotentialPriceTotal == input.PotentialPriceTotal ||
                    (this.PotentialPriceTotal != null &&
                    this.PotentialPriceTotal.Equals(input.PotentialPriceTotal))
                ) && 
                (
                    this.Manufacturer == input.Manufacturer ||
                    (this.Manufacturer != null &&
                    this.Manufacturer.Equals(input.Manufacturer))
                ) && 
                (
                    this.VatSum == input.VatSum ||
                    (this.VatSum != null &&
                    this.VatSum.Equals(input.VatSum))
                ) && 
                (
                    this.Ingredients == input.Ingredients ||
                    (this.Ingredients != null &&
                    this.Ingredients.Equals(input.Ingredients))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.PackageAmount == input.PackageAmount ||
                    (this.PackageAmount != null &&
                    this.PackageAmount.Equals(input.PackageAmount))
                ) && 
                (
                    this.StorageConditions == input.StorageConditions ||
                    (this.StorageConditions != null &&
                    this.StorageConditions.Equals(input.StorageConditions))
                ) && 
                (
                    this.StoragePeriod == input.StoragePeriod ||
                    (this.StoragePeriod != null &&
                    this.StoragePeriod.Equals(input.StoragePeriod))
                ) && 
                (
                    this.Weight == input.Weight ||
                    (this.Weight != null &&
                    this.Weight.Equals(input.Weight))
                ) && 
                (
                    this.Brand == input.Brand ||
                    (this.Brand != null &&
                    this.Brand.Equals(input.Brand))
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.Group == input.Group ||
                    (this.Group != null &&
                    this.Group.Equals(input.Group))
                ) && 
                (
                    this.Edl == input.Edl ||
                    (this.Edl != null &&
                    this.Edl.Equals(input.Edl))
                ) && 
                (
                    this.Seasonal == input.Seasonal ||
                    (this.Seasonal != null &&
                    this.Seasonal.Equals(input.Seasonal))
                ) && 
                (
                    this.Inn == input.Inn ||
                    (this.Inn != null &&
                    this.Inn.Equals(input.Inn))
                ) && 
                (
                    this.TvAdv == input.TvAdv ||
                    (this.TvAdv != null &&
                    this.TvAdv.Equals(input.TvAdv))
                ) && 
                (
                    this.Novelty == input.Novelty ||
                    (this.Novelty != null &&
                    this.Novelty.Equals(input.Novelty))
                ) && 
                (
                    this.Bestseller == input.Bestseller ||
                    (this.Bestseller != null &&
                    this.Bestseller.Equals(input.Bestseller))
                ) && 
                (
                    this.Offers == input.Offers ||
                    this.Offers != null &&
                    input.Offers != null &&
                    this.Offers.SequenceEqual(input.Offers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UniqueId != null)
                    hashCode = hashCode * 59 + this.UniqueId.GetHashCode();
                if (this.ProductId != null)
                    hashCode = hashCode * 59 + this.ProductId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Ean != null)
                    hashCode = hashCode * 59 + this.Ean.GetHashCode();
                if (this.Gtin != null)
                    hashCode = hashCode * 59 + this.Gtin.GetHashCode();
                if (this.Vat != null)
                    hashCode = hashCode * 59 + this.Vat.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                if (this.PriceWithVAT != null)
                    hashCode = hashCode * 59 + this.PriceWithVAT.GetHashCode();
                if (this.DistributorId != null)
                    hashCode = hashCode * 59 + this.DistributorId.GetHashCode();
                if (this.ExpirationDate != null)
                    hashCode = hashCode * 59 + this.ExpirationDate.GetHashCode();
                if (this.Quantity != null)
                    hashCode = hashCode * 59 + this.Quantity.GetHashCode();
                if (this.MinOrder != null)
                    hashCode = hashCode * 59 + this.MinOrder.GetHashCode();
                if (this.Multiplicity != null)
                    hashCode = hashCode * 59 + this.Multiplicity.GetHashCode();
                if (this.Bonus != null)
                    hashCode = hashCode * 59 + this.Bonus.GetHashCode();
                if (this.Discount != null)
                    hashCode = hashCode * 59 + this.Discount.GetHashCode();
                if (this.PotentialPriceWithOffers != null)
                    hashCode = hashCode * 59 + this.PotentialPriceWithOffers.GetHashCode();
                if (this.IsOffer != null)
                    hashCode = hashCode * 59 + this.IsOffer.GetHashCode();
                if (this.BonusMaxMonthOrderAmount != null)
                    hashCode = hashCode * 59 + this.BonusMaxMonthOrderAmount.GetHashCode();
                if (this.PotentialPriceTotal != null)
                    hashCode = hashCode * 59 + this.PotentialPriceTotal.GetHashCode();
                if (this.Manufacturer != null)
                    hashCode = hashCode * 59 + this.Manufacturer.GetHashCode();
                if (this.VatSum != null)
                    hashCode = hashCode * 59 + this.VatSum.GetHashCode();
                if (this.Ingredients != null)
                    hashCode = hashCode * 59 + this.Ingredients.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.PackageAmount != null)
                    hashCode = hashCode * 59 + this.PackageAmount.GetHashCode();
                if (this.StorageConditions != null)
                    hashCode = hashCode * 59 + this.StorageConditions.GetHashCode();
                if (this.StoragePeriod != null)
                    hashCode = hashCode * 59 + this.StoragePeriod.GetHashCode();
                if (this.Weight != null)
                    hashCode = hashCode * 59 + this.Weight.GetHashCode();
                if (this.Brand != null)
                    hashCode = hashCode * 59 + this.Brand.GetHashCode();
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.Group != null)
                    hashCode = hashCode * 59 + this.Group.GetHashCode();
                if (this.Edl != null)
                    hashCode = hashCode * 59 + this.Edl.GetHashCode();
                if (this.Seasonal != null)
                    hashCode = hashCode * 59 + this.Seasonal.GetHashCode();
                if (this.Inn != null)
                    hashCode = hashCode * 59 + this.Inn.GetHashCode();
                if (this.TvAdv != null)
                    hashCode = hashCode * 59 + this.TvAdv.GetHashCode();
                if (this.Novelty != null)
                    hashCode = hashCode * 59 + this.Novelty.GetHashCode();
                if (this.Bestseller != null)
                    hashCode = hashCode * 59 + this.Bestseller.GetHashCode();
                if (this.Offers != null)
                    hashCode = hashCode * 59 + this.Offers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {

            // UniqueId (string) minLength
            if(this.UniqueId != null && this.UniqueId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UniqueId, length must be greater than 1.", new [] { "UniqueId" });
            }


            // Name (string) minLength
            if(this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }


            // Ean (string) minLength
            if(this.Ean != null && this.Ean.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Ean, length must be greater than 1.", new [] { "Ean" });
            }


            // Gtin (string) minLength
            if(this.Gtin != null && this.Gtin.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Gtin, length must be greater than 1.", new [] { "Gtin" });
            }


            // Manufacturer (string) minLength
            if(this.Manufacturer != null && this.Manufacturer.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Manufacturer, length must be greater than 1.", new [] { "Manufacturer" });
            }


            // Ingredients (string) minLength
            if(this.Ingredients != null && this.Ingredients.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Ingredients, length must be greater than 1.", new [] { "Ingredients" });
            }


            // Country (string) minLength
            if(this.Country != null && this.Country.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Country, length must be greater than 1.", new [] { "Country" });
            }


            // StorageConditions (string) minLength
            if(this.StorageConditions != null && this.StorageConditions.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StorageConditions, length must be greater than 1.", new [] { "StorageConditions" });
            }


            // Brand (string) minLength
            if(this.Brand != null && this.Brand.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Brand, length must be greater than 1.", new [] { "Brand" });
            }


            // Category (string) minLength
            if(this.Category != null && this.Category.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Category, length must be greater than 1.", new [] { "Category" });
            }


            // Group (string) minLength
            if(this.Group != null && this.Group.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Group, length must be greater than 1.", new [] { "Group" });
            }

            yield break;
        }
    }

}
