/*
 * API для аптечных сетей
 *
 * Авторизация по токену, используйте заголовок          Authorization: Bearer токен         пример:          Authorization: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU          Для того чтобы работать с API через интерфейс swagger (ниже, по кнопке Try it out),         нажмите кнопку Authorize и укажите токен в формате Bearer токен.         Пример: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU 
 *
 * The version of the OpenAPI document: v2
 * Contact: info@pharm-zakaz.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ListDistributors
    /// </summary>
    [DataContract]
    public partial class ListDistributors :  IEquatable<ListDistributors>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListDistributors" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListDistributors() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListDistributors" /> class.
        /// </summary>
        /// <param name="distributorId">distributorId (required).</param>
        /// <param name="distributorName">distributorName (required).</param>
        public ListDistributors(int distributorId = default(int), string distributorName = default(string))
        {
            // to ensure "distributorId" is required (not null)
            if (distributorId == null)
            {
                throw new InvalidDataException("distributorId is a required property for ListDistributors and cannot be null");
            }
            else
            {
                this.DistributorId = distributorId;
            }

            // to ensure "distributorName" is required (not null)
            if (distributorName == null)
            {
                throw new InvalidDataException("distributorName is a required property for ListDistributors and cannot be null");
            }
            else
            {
                this.DistributorName = distributorName;
            }

        }

        /// <summary>
        /// Gets or Sets DistributorId
        /// </summary>
        [DataMember(Name="distributor_id", EmitDefaultValue=true)]
        public int DistributorId { get; set; }

        /// <summary>
        /// Gets or Sets DistributorName
        /// </summary>
        [DataMember(Name="distributor_name", EmitDefaultValue=true)]
        public string DistributorName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListDistributors {\n");
            sb.Append("  DistributorId: ").Append(DistributorId).Append("\n");
            sb.Append("  DistributorName: ").Append(DistributorName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListDistributors);
        }

        /// <summary>
        /// Returns true if ListDistributors instances are equal
        /// </summary>
        /// <param name="input">Instance of ListDistributors to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListDistributors input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DistributorId == input.DistributorId ||
                    (this.DistributorId != null &&
                    this.DistributorId.Equals(input.DistributorId))
                ) && 
                (
                    this.DistributorName == input.DistributorName ||
                    (this.DistributorName != null &&
                    this.DistributorName.Equals(input.DistributorName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DistributorId != null)
                    hashCode = hashCode * 59 + this.DistributorId.GetHashCode();
                if (this.DistributorName != null)
                    hashCode = hashCode * 59 + this.DistributorName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {

            // DistributorName (string) minLength
            if(this.DistributorName != null && this.DistributorName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DistributorName, length must be greater than 1.", new [] { "DistributorName" });
            }

            yield break;
        }
    }

}
