/*
 * API для аптечных сетей
 *
 * Авторизация по токену, используйте заголовок          Authorization: Bearer токен         пример:          Authorization: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU          Для того чтобы работать с API через интерфейс swagger (ниже, по кнопке Try it out),         нажмите кнопку Authorize и укажите токен в формате Bearer токен.         Пример: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU 
 *
 * The version of the OpenAPI document: v2
 * Contact: info@pharm-zakaz.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ListDistributors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListDistributorsTests
    {
        // TODO uncomment below to declare an instance variable for ListDistributors
        //private ListDistributors instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListDistributors
            //instance = new ListDistributors();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListDistributors
        /// </summary>
        [Test]
        public void ListDistributorsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListDistributors
            //Assert.IsInstanceOf(typeof(ListDistributors), instance);
        }


        /// <summary>
        /// Test the property 'DistributorId'
        /// </summary>
        [Test]
        public void DistributorIdTest()
        {
            // TODO unit test for the property 'DistributorId'
        }
        /// <summary>
        /// Test the property 'DistributorName'
        /// </summary>
        [Test]
        public void DistributorNameTest()
        {
            // TODO unit test for the property 'DistributorName'
        }

    }

}
