/*
 * API для аптечных сетей
 *
 * Авторизация по токену, используйте заголовок          Authorization: Bearer токен         пример:          Authorization: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU          Для того чтобы работать с API через интерфейс swagger (ниже, по кнопке Try it out),         нажмите кнопку Authorize и укажите токен в формате Bearer токен.         Пример: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU 
 *
 * The version of the OpenAPI document: v2
 * Contact: info@pharm-zakaz.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Offer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OfferTests
    {
        // TODO uncomment below to declare an instance variable for Offer
        //private Offer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Offer
            //instance = new Offer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Offer
        /// </summary>
        [Test]
        public void OfferInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Offer
            //Assert.IsInstanceOf(typeof(Offer), instance);
        }


        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Test]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }
        /// <summary>
        /// Test the property 'OrderMin'
        /// </summary>
        [Test]
        public void OrderMinTest()
        {
            // TODO unit test for the property 'OrderMin'
        }
        /// <summary>
        /// Test the property 'Multiplicity'
        /// </summary>
        [Test]
        public void MultiplicityTest()
        {
            // TODO unit test for the property 'Multiplicity'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'Bonus'
        /// </summary>
        [Test]
        public void BonusTest()
        {
            // TODO unit test for the property 'Bonus'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'PriceWithVAT'
        /// </summary>
        [Test]
        public void PriceWithVATTest()
        {
            // TODO unit test for the property 'PriceWithVAT'
        }
        /// <summary>
        /// Test the property 'Vat'
        /// </summary>
        [Test]
        public void VatTest()
        {
            // TODO unit test for the property 'Vat'
        }

    }

}
