/*
 * API для аптечных сетей
 *
 * Авторизация по токену, используйте заголовок          Authorization: Bearer токен         пример:          Authorization: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU          Для того чтобы работать с API через интерфейс swagger (ниже, по кнопке Try it out),         нажмите кнопку Authorize и укажите токен в формате Bearer токен.         Пример: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU 
 *
 * The version of the OpenAPI document: v2
 * Contact: info@pharm-zakaz.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OrderItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderItemTests
    {
        // TODO uncomment below to declare an instance variable for OrderItem
        //private OrderItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderItem
            //instance = new OrderItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderItem
        /// </summary>
        [Test]
        public void OrderItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" OrderItem
            //Assert.IsInstanceOf(typeof(OrderItem), instance);
        }


        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Test]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }
        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Test]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Ean'
        /// </summary>
        [Test]
        public void EanTest()
        {
            // TODO unit test for the property 'Ean'
        }
        /// <summary>
        /// Test the property 'Gtin'
        /// </summary>
        [Test]
        public void GtinTest()
        {
            // TODO unit test for the property 'Gtin'
        }
        /// <summary>
        /// Test the property 'Vat'
        /// </summary>
        [Test]
        public void VatTest()
        {
            // TODO unit test for the property 'Vat'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'PriceWithVAT'
        /// </summary>
        [Test]
        public void PriceWithVATTest()
        {
            // TODO unit test for the property 'PriceWithVAT'
        }
        /// <summary>
        /// Test the property 'DistributorId'
        /// </summary>
        [Test]
        public void DistributorIdTest()
        {
            // TODO unit test for the property 'DistributorId'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'MinOrder'
        /// </summary>
        [Test]
        public void MinOrderTest()
        {
            // TODO unit test for the property 'MinOrder'
        }
        /// <summary>
        /// Test the property 'Multiplicity'
        /// </summary>
        [Test]
        public void MultiplicityTest()
        {
            // TODO unit test for the property 'Multiplicity'
        }
        /// <summary>
        /// Test the property 'Bonus'
        /// </summary>
        [Test]
        public void BonusTest()
        {
            // TODO unit test for the property 'Bonus'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'PotentialPriceWithOffers'
        /// </summary>
        [Test]
        public void PotentialPriceWithOffersTest()
        {
            // TODO unit test for the property 'PotentialPriceWithOffers'
        }
        /// <summary>
        /// Test the property 'IsOffer'
        /// </summary>
        [Test]
        public void IsOfferTest()
        {
            // TODO unit test for the property 'IsOffer'
        }
        /// <summary>
        /// Test the property 'BonusMaxMonthOrderAmount'
        /// </summary>
        [Test]
        public void BonusMaxMonthOrderAmountTest()
        {
            // TODO unit test for the property 'BonusMaxMonthOrderAmount'
        }
        /// <summary>
        /// Test the property 'PotentialPriceTotal'
        /// </summary>
        [Test]
        public void PotentialPriceTotalTest()
        {
            // TODO unit test for the property 'PotentialPriceTotal'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'ProductSum'
        /// </summary>
        [Test]
        public void ProductSumTest()
        {
            // TODO unit test for the property 'ProductSum'
        }
        /// <summary>
        /// Test the property 'ProductSumWithVat'
        /// </summary>
        [Test]
        public void ProductSumWithVatTest()
        {
            // TODO unit test for the property 'ProductSumWithVat'
        }

    }

}
