/*
 * API для аптечных сетей
 *
 * Авторизация по токену, используйте заголовок          Authorization: Bearer токен         пример:          Authorization: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU          Для того чтобы работать с API через интерфейс swagger (ниже, по кнопке Try it out),         нажмите кнопку Authorize и укажите токен в формате Bearer токен.         Пример: Bearer iJKLCJhbGciOiwIjoxN3MzM0zUw9zDuGk4-sYMmf9L_8WRU 
 *
 * The version of the OpenAPI document: v2
 * Contact: info@pharm-zakaz.ru
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ResponseOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseOrderTests
    {
        // TODO uncomment below to declare an instance variable for ResponseOrder
        //private ResponseOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseOrder
            //instance = new ResponseOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseOrder
        /// </summary>
        [Test]
        public void ResponseOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ResponseOrder
            //Assert.IsInstanceOf(typeof(ResponseOrder), instance);
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'OrderCode'
        /// </summary>
        [Test]
        public void OrderCodeTest()
        {
            // TODO unit test for the property 'OrderCode'
        }
        /// <summary>
        /// Test the property 'DistributorOrderId'
        /// </summary>
        [Test]
        public void DistributorOrderIdTest()
        {
            // TODO unit test for the property 'DistributorOrderId'
        }
        /// <summary>
        /// Test the property 'StatusDelivery'
        /// </summary>
        [Test]
        public void StatusDeliveryTest()
        {
            // TODO unit test for the property 'StatusDelivery'
        }
        /// <summary>
        /// Test the property 'DelayedItems'
        /// </summary>
        [Test]
        public void DelayedItemsTest()
        {
            // TODO unit test for the property 'DelayedItems'
        }

    }

}
